/*
  Auto-generated by Spline
*/

import { OrthographicCamera } from "@react-three/drei";
import useSpline from "@splinetool/r3f-spline";

export default function Lanyard({ ...props }) {
  const { nodes, materials } = useSpline("loading...");
  return (
    <>
      <color attach="background" args={["#000000"]} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <group
            name="Group 2"
            position={[-45.39, 81.07, 16.39]}
            rotation={[0, 0, 0.07]}
            scale={[0.21, 0.21, 1]}
          >
            <mesh
              name="Shape 0"
              geometry={nodes["Shape 0"].geometry}
              material={materials["Shape 0 Material"]}
              castShadow
              receiveShadow
              position={[-228.5, 269.5, 0]}
            />
          </group>
          <group
            name="Group"
            position={[-45.39, 81.07, 14.25]}
            rotation={[0, 0, -0.03]}
            scale={[0.21, 0.21, 1]}
          >
            <mesh
              name="Shape 01"
              geometry={nodes["Shape 01"].geometry}
              material={materials["Shape 01 Material"]}
              castShadow
              receiveShadow
              position={[-228.5, 269.5, 0]}
            />
          </group>
          <mesh
            name="Boolean"
            geometry={nodes.Boolean.geometry}
            material={nodes.Boolean.material}
            castShadow
            receiveShadow
            position={[-44.3, 87.41, 21.82]}
            rotation={[0, 0, -0.01]}
            scale={[1.06, 1.53, 5.05]}
          />
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[200, 300, 300]}
          />
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  );
}
